baseurl = "/"
title = "CUPE Retirees Association"
languageCode = "en-us"
paginate = "10" # Number of posts per page
theme = "mainroad"
disqusShortname = "" # Enable comments by entering your Disqus shortname
googleAnalytics = "" # Enable Google Analytics by entering your tracking id

[languages]

  [languages.en]
    contentDir = "content/english"
    title = "CUPE Retirees Association"
    subtitle = "subtitle"
    languageName = "English"
    weight = 10


  [languages.fr]
    contentDir = "content/french"
    title = "Association des retraités du SCFP"
    subtitle = "sub title french"
    languageName = "Français"
    weight = 20


[Author]
  name = "CUPE Retirees Association"
  bio = "The CUPE Retirees Association atcs as the voice of retirees with CUPE and the unions representing CUPE staff."
  avatar = "img/avatar.png"

[Params]
  description = "The CUPE Retirees Association atcs as the voice of retirees with CUPE and the unions representing CUPE staff." # Description of your site
  opengraph = true
  twitter_cards = false
  readmore = true # Show "Read more" button in list if true
  authorbox = true
  pager = true
  post_meta = ["date", "categories","translations"] # Order of post meta information

[Params.logo]
#  subtitle = "CUPE Retirees Association" # Logo subtitle

[Params.sidebar]
  home = "right"   # Configure layout for home page
  list = "right"   # Configure layout for list pages
  single = "right" # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "recent", "categories", "taglist","languages"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)
