backend:
  name: github
  branch: main
  site_url: https://cuperetirees.ca
  repo: citizenspress/cuperetirees # Path to your GitHub repository
  
publish_mode: editorial_workflow

media_folder: 'static/img/'
public_folder: 'img'
collections:
  - name: posts
    label: Posts
    label_singular: Post
    folder: 'content/post'
#    path: '{{slug}}'
    create: true  # Allow users to create new documents in this collection
    fields:  # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Subtitle", name: "subtitle", widget: "string"}
      - {label: "Summary", name: "lead", widget: "markdown"}
      - label: "Draft"
        name: "draft"
        required: false
        widget: "boolean"
        default: false
      - label: "Tags"
        name: "tags"
        required: false
        widget: "list"
      - label: "Categories"
        name: "categories"
        required: false
        widget: "list"
      - label: "Featured Image"
        name: "thumbnail"
        widget: object
        fields:
          - label: "Upload an image named `featured.jpg/png`"
            name: "filename"
            widget: "image"
            default: "featured"
            media_library:
              config:
                multiple: false
          - {label: Caption, name: caption, widget: string, required: false}
          - {label: Description for screen readers, name: alt_text, widget: string, required: false}
      - {label: "Body", name: "body", widget: "markdown"}
